Sprint 10
SnakeAssassin/ImageFeed pull request #3
Opened 2024-02-02 12:49 UTC by SnakeAssassin

Для входа в приложение пользователь авторизуется через OAuth2.0
В проекте создан файл Constants.swift, в нём есть константы AccessKey, SecretKey, RedirectURI и AccessScope
Свёрстан контроллер WebView, его дизайн соответствует ТЗ
Реализован KVO — приложение показывает, как обновляется прогресс загрузки веб-страницы.
Проверка необходимости авторизации выделена в отдельный контроллер SplashViewController
Добавлена структура для декодинга JSON-ответа от [POST-запроса авторизации] Unsplash — OAuthTokenResponseBody
Создан новый класс OAuth2Service

При первом запуске приложения пользователь должен увидеть SplashViewController, а затем — форму авторизации.
При повторном запуске (после ранее успешной авторизации) пользователь сразу после SplashViewController попадает в галерею.

2024-02-02 22:12 UTC, protos17 requested changes

2024-02-02 22:12 UTC, protos17 commented on ImageFeed.xcodeproj/project.pbxproj
> +		};
Связи с папкой Trash остались, хоть файлы и отсутствуют. Если сумеешь, можешь удалить здесь эти строки, запустить и проверить код

2024-02-02 22:12 UTC, protos17 commented on ImageFeed/Auth/AuthViewController.swift
> +    private let ShowWebViewSegueIdentifier = "ShowWebView"
Константы принято писать с маленькой буквы

2024-02-02 22:12 UTC, protos17 commented on ImageFeed/Auth/AuthViewController.swift
> +    @objc func didTapButton() {
Здесь стоит добавить `private`
Необходимо указывать private  для того, чтобы спрятать детали реализации конкретной части функциональности, когда они используются только внутри области объявления.

2024-02-02 22:12 UTC, protos17 commented on ImageFeed/Auth/AuthViewController.swift
> +        button.setTitleColor(UIColor(named: "YP Gray"), for: .highlighted)
Работу с цветами рекомендую перенести в extension UIColor

2024-02-02 22:12 UTC, protos17 commented on ImageFeed/Auth/AuthViewController.swift
> +            else { fatalError("Failed to prepare for \(ShowWebViewSegueIdentifier)") }
Хочу отметить, что в продакшене не используется `fatalError`, кроме случаев, когда это необходимо, например, в банковском приложении при обнаружении джейлбрейка.

2024-02-02 22:12 UTC, protos17 commented on ImageFeed/Auth/WebViewViewController.swift
> +    fileprivate let UnsplashAuthorizeURLString = "https://unsplash.com/oauth/authorize"
Рекомендую написать с маленькой буквы и перенести в Constants. Внутри класса переменные и константы стоит указывать как private, а не fileprivate

2024-02-02 22:12 UTC, protos17 commented on ImageFeed/Auth/WebViewViewController.swift
> +    @objc func didTapButton() {
Рекомендую указать как private

2024-02-02 22:12 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListViewController.swift
>      private let ShowSingleImageSegueIdentifier = "ShowSingleImage"
Рекомендую указать как private

2024-02-02 22:12 UTC, protos17 commented on ImageFeed/OAuth2/OAuth2Service.swift
> +    static let shared = OAuth2Service()
Рекомендую при использовании синглтонов указывать еще:

     private init() {}

это гарантирует, что не будет создан новый экземпляр класса, кроме shared

2024-02-02 22:12 UTC, protos17 commented on ImageFeed/OAuth2/OAuth2Service.swift
> +
Рекомендую убрать лишний отступ

2024-02-02 22:12 UTC, protos17 commented on ImageFeed/OAuth2/OAuth2Service.swift
> +
Рекомендую оставлять всегда не более 1 отступа

2024-02-02 22:12 UTC, protos17 commented on ImageFeed/OAuth2/OAuth2Service.swift
> +            baseURL: URL(string: "https://unsplash.com")!
Рекомендую указать в Constants

2024-02-02 22:12 UTC, protos17 commented on ImageFeed/OAuth2/OAuth2Service.swift
> +
Рекомендую оставить только 1 отступ

2024-02-02 22:12 UTC, protos17 commented on ImageFeed/OAuth2/OAuth2Service.swift
> +fileprivate let DefaultBaseURL = URL(string: "https://api.unsplash.com")!
Рекомендую написать с маленькой буквы и перенести в Constants

2024-02-02 22:12 UTC, protos17 commented on ImageFeed/OAuth2/OAuth2TokenStorage.swift
> +    static let shared = OAuth2TokenStorage() // Синглтон
Чтобы гарантировать, что не будет создан другой экземпляр класса, необходимо указать приватный инициализатор:

     private init() {}

2024-02-02 22:12 UTC, protos17 commented on ImageFeed/SingleImageView/SingleImageViewController.swift
>      @IBOutlet weak var scrollView: UIScrollView!
Рекомендую указать как private

2024-02-02 22:12 UTC, protos17 commented on ImageFeed/SplashViewController/SplashViewController.swift
> +    private let TabBarViewControllerIdentifier = "TabBarViewController"
Константы принято писать с маленькой буквы

2024-02-03 08:30 UTC, SnakeAssassin commented on ImageFeed.xcodeproj/project.pbxproj
> +		};
Извиняюсь, почему то отправился промежуточный код,  с моими комментариями и не до конца удаленными временными файлами.

2024-02-03 08:30 UTC, SnakeAssassin commented on ImageFeed.xcodeproj/project.pbxproj
> +		};
> Связи с папкой Trash остались, хоть файлы и отсутствуют. Если сумеешь, можешь удалить здесь эти строки, запустить и проверить код

Извиняюсь, почему то отправился промежуточный код, с моими комментариями и не до конца удаленными временными файлами.

2024-02-03 13:06 UTC, protos17 approved these changes

2024-02-03 13:06 UTC, protos17 commented on ImageFeed/Auth/AuthViewController.swift
> +                // fatalError("Failed to prepare for \(showWebViewSegueIdentifier)")
Лишний закомментированный код рекомендую удалять

2024-02-03 13:06 UTC, protos17 commented on ImageFeed/Resources/Constants.swift
> +let UnsplashAuthorizeURLString = "https://unsplash.com/oauth/authorize"
Рекомендую вынести в enum и обращаться через static let:

      enum Constants {
           static let accessKey = ""
           ...
      }

2024-02-04 14:29 UTC, merged